import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./styles.css';
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const sb=createClient(supabaseUrl,supabaseKey);
type Song={id:string;title:string;artist:string;album:string;url:string;storage_path:string;favorite:boolean;is_public:boolean;lastPlayed?:number};type Playlist={id:string;name:string;songIds:string[]};type Tab='home'|'search'|'library'|'playlists'|'profile';
const id=()=>crypto.randomUUID(),fmt=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const Icon=({n}:{n:string})=><span className="ico">{({home:'⌂',search:'⌕',music:'♫',list:'☷',user:'◯',plus:'＋',play:'▶',pause:'Ⅱ',next:'▶|',prev:'|◀',heart:'♥',shuffle:'⤨',repeat:'↻',trash:'⌫',back:'‹'}as any)[n]||'•'})</span>;
function Cover({url,big=false}:{url?:string,big?:boolean}){return <div className={'cover '+(big?'big':'')}>{url?<img src={url} onError={e=>(e.currentTarget.style.display='none')}/>:<span>♫</span>}</div>}
async function signedSongs(rows:any[]){return Promise.all(rows.map(async r=>{const {data}=await sb.storage.from('songs').createSignedUrl(r.storage_path,60*60);return {...r,url:data?.signedUrl||'',lastPlayed:r.last_played?new Date(r.last_played).getTime():undefined}}))}
function Auth(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'signup'>('login'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');const submit=async()=>{setBusy(true);setMsg('');const r=mode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});setBusy(false);if(r.error)setMsg(r.error.message);else setMsg(mode==='signup'?'Akun dibuat. Cek email jika konfirmasi email diaktifkan.':'Berhasil masuk.')};return <div className="auth"><div className="authcard"><div className="brand"><b>GW</b><span>GAMEWAVE<small>MUSIC</small></span></div><small>{mode==='login'?'CLOUD MUSIC LOGIN':'CREATE YOUR ACCOUNT'}</small><h1>{mode==='login'?'Welcome back.':'Create account.'}</h1><p>Masuk untuk menyimpan lagu dan playlist di cloud.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/><button className="primary" disabled={busy||!email||!password} onClick={submit}>{busy?'Please wait…':mode==='login'?'Sign in':'Sign up'}</button>{msg&&<div className="note">{msg}</div>}<button className="textbtn" onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Belum punya akun? Sign up':'Sudah punya akun? Sign in'}</button></div></div>}
export default function App(){const[a,setA]=useState<Song[]>([]),[p,setP]=useState<Playlist[]>([]),[tab,setTab]=useState<Tab>('home'),[q,setQ]=useState(''),[cur,setCur]=useState<Song>(),[queue,setQueue]=useState<Song[]>([]),[qi,setQi]=useState(0),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[dur,setDur]=useState(0),[shuffle,setShuffle]=useState(false),[repeat,setRepeat]=useState(false),[full,setFull]=useState(false),[toast,setToast]=useState(''),[uploadPublic,setUploadPublic]=useState(false),[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true);const audio=useRef<HTMLAudioElement>();const file=useRef<HTMLInputElement>(null);
useEffect(()=>{sb.auth.getSession().then(({data}:any)=>{setSession(data.session);setLoading(false)});const {data}=sb.auth.onAuthStateChange((_e:any,s:any)=>{setSession(s);setLoading(false)});return()=>data.subscription.unsubscribe()},[]);
const refresh=async()=>{if(!session)return;const {data,error}=await sb.from('songs').select('*').order('created_at',{ascending:false});if(!error)setA(await signedSongs(data||[]));const {data:ps}=await sb.from('playlists').select('id,name').order('created_at',{ascending:false});if(ps){const out:Playlist[]=[];for(const x of ps){const {data:ids}=await sb.from('playlist_songs').select('song_id').eq('playlist_id',x.id);out.push({...x,songIds:(ids||[]).map((z:any)=>z.song_id)})}setP(out)}};
useEffect(()=>{if(session)refresh();else{setA([]);setP([])}},[session]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)},[toast]);
const play=(s:Song,list=a)=>{const i=Math.max(0,list.findIndex(x=>x.id===s.id));setQueue(list);setQi(i);setCur(list[i]);sb.from('songs').update({last_played:new Date().toISOString()}).eq('id',s.id).then(()=>{});};
useEffect(()=>{if(!cur)return;audio.current?.pause();const x=new Audio(cur.url);audio.current=x;x.onloadedmetadata=()=>setDur(x.duration||0);x.ontimeupdate=()=>setPos(x.currentTime);x.onplay=()=>setPlaying(true);x.onpause=()=>setPlaying(false);x.onended=()=>next();x.play().catch(()=>{});return()=>{x.pause() }},[cur]);
const next=()=>{if(!queue.length)return;let n=qi+1;if(shuffle&&queue.length>1)do n=Math.floor(Math.random()*queue.length);while(n===qi);if(n>=queue.length){if(!repeat)return;n=0}setQi(n);setCur(queue[n])};const prev=()=>{if(!audio.current)return;if(pos>3){audio.current.currentTime=0;return}let n=qi-1;if(n<0){if(!repeat)return;n=queue.length-1}setQi(n);setCur(queue[n])};
const importMusic=async(fs:FileList|null)=>{if(!fs||!session)return;let n=0;for(const f of Array.from(fs)){if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav|flac|ogg|opus)$/i.test(f.name))continue;const songId=id(),ext=f.name.includes('.')?f.name.split('.').pop():'bin',path=`${session.user.id}/${songId}.${ext}`;const up=await sb.storage.from('songs').upload(path,f,{upsert:false,contentType:f.type||'audio/mpeg'});if(up.error){setToast(up.error.message);continue}const ins=await sb.from('songs').insert({id:songId,user_id:session.user.id,title:f.name.replace(/\.[^.]+$/,''),artist:'Unknown Artist',album:'Cloud Music',storage_path:path,mime_type:f.type||null,favorite:false,is_public:uploadPublic});if(ins.error){await sb.storage.from('songs').remove([path]);setToast(ins.error.message);continue}n++}await refresh();setToast(`${n} lagu berhasil disimpan ke cloud.`)};
const togglePublic=async(s:Song)=>{const r=await sb.from('songs').update({is_public:!s.is_public}).eq('id',s.id).eq('user_id',session.user.id);if(r.error)setToast(r.error.message);else{await refresh();setToast(!s.is_public?'Lagu sekarang publik. Perangkat lain dapat melihat dan memutarnya.':'Lagu sekarang privat.')}};const fav=async(s:Song)=>{await sb.from('songs').update({favorite:!s.favorite}).eq('id',s.id);await refresh()};const remove=async(s:Song)=>{if(!confirm(`Hapus "${s.title}" dari cloud?`))return;await sb.storage.from('songs').remove([s.storage_path]);await sb.from('songs').delete().eq('id',s.id);if(cur?.id===s.id){audio.current?.pause();setCur(undefined);setFull(false)}await refresh()};
const create=async()=>{const name=prompt('Nama playlist:');if(!name||!session)return;const playlistId=id();await sb.from('playlists').insert({id:playlistId,user_id:session.user.id,name});await refresh()};const add=async(s:Song)=>{if(!p.length){setToast('Buat playlist terlebih dahulu.');return}const n=prompt('Nomor playlist:\n'+p.map((x,i)=>`${i+1}. ${x.name}`).join('\n'));const x=p[Number(n)-1];if(!x)return;if(x.songIds.includes(s.id))return setToast('Lagu sudah ada di playlist.');const r=await sb.from('playlist_songs').insert({playlist_id:x.id,song_id:s.id,user_id:session.user.id});if(r.error)setToast(r.error.message);else{await refresh();setToast('Ditambahkan ke playlist.')}};
const filtered=useMemo(()=>a.filter(s=>(s.title+' '+s.artist+' '+s.album).toLowerCase().includes(q.toLowerCase())),[a,q]);const recent=[...a].filter(s=>s.lastPlayed).sort((x,y)=>(y.lastPlayed||0)-(x.lastPlayed||0)).slice(0,6);const favs=a.filter(x=>x.favorite);
if(loading)return <div className="auth"><div className="authcard"><h2>Loading GameWave…</h2></div></div>;if(!session)return <Auth/>;
return <div className="app"><header><div className="brand"><b>GW</b><span>GAMEWAVE<small>MUSIC</small></span></div><label className="public-toggle"><input type="checkbox" checked={uploadPublic} onChange={e=>setUploadPublic(e.target.checked)}/> Public saat upload</label><button onClick={()=>file.current?.click()}><Icon n="plus"/></button><input ref={file} hidden type="file" multiple accept="audio/*,.flac,.wav" onChange={e=>importMusic(e.target.files)}/></header><main>
{tab==='home'&&<><div className="welcome"><div><small>YOUR PERSONAL SOUNDTRACK</small><h1>Good evening.</h1><p>Cloud music untuk akunmu.</p></div><button className="primary" onClick={()=>file.current?.click()}><Icon n="plus"/> Add Music</button></div>{(recent[0]||a[0])?<div className="hero" onClick={()=>{play(recent[0]||a[0]);setFull(true)}}><Cover url={(recent[0]||a[0]).url} big/><div><small>CONTINUE LISTENING</small><h2>{(recent[0]||a[0]).title}</h2><p>{(recent[0]||a[0]).artist}</p><button className="round"><Icon n="play"/></button></div></div>:<div className="empty"><h2>Library masih kosong</h2><p>Import musik dan file akan disimpan di cloud akunmu.</p><button className="primary" onClick={()=>file.current?.click()}>Import Music</button></div>}<h2 className="sect">Quick Access</h2><div className="quick"><button onClick={()=>favs[0]&&play(favs[0],favs)}><b>♥ Favorites</b><small>{favs.length} tracks</small></button><button onClick={()=>a[0]&&play(a[0],a)}><b>♫ All Music</b><small>{a.length} tracks</small></button></div>{recent.length>0&&<><h2 className="sect">Recently Played</h2><Rows list={recent} play={play}/></>}</>}
{tab==='search'&&<><div className="search"><Icon n="search"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, artist, album..."/></div><Rows list={filtered} play={play} fav={fav} add={add} remove={remove} togglePublic={togglePublic}/></>}
{tab==='library'&&<><div className="title"><div><small>CLOUD LIBRARY</small><h1>My Music</h1><p>{a.length} tracks</p></div><button className="primary" onClick={()=>file.current?.click()}>＋ Add Music</button></div>{a.length?<Rows list={a} play={play} fav={fav} add={add} remove={remove} togglePublic={togglePublic}/>:<div className="empty"><h2>No tracks yet</h2><button className="primary" onClick={()=>file.current?.click()}>Add your first song</button></div>}</>}
{tab==='playlists'&&<Playlists ps={p} songs={a} create={create} play={play}/>} {tab==='profile'&&<Profile songs={a} ps={p} email={session.user.email||''} signOut={()=>sb.auth.signOut()}/>}</main>
{cur&&<div className="mini"><button onClick={()=>setFull(true)}><Cover url={cur.url}/></button><div onClick={()=>setFull(true)}><b>{cur.title}</b><small>{cur.artist}</small></div><button onClick={()=>playing?audio.current?.pause():audio.current?.play()}><Icon n={playing?'pause':'play'}/></button><button onClick={next}><Icon n="next"/></button><i><span style={{width:`${dur?pos/dur*100:0}%`}}/></i></div>}
<nav>{([['home','Home'],['search','Search'],['library','Library'],['playlists','Playlists'],['profile','Profile']] as const).map(([x,t])=><button className={tab===x?'on':''} onClick={()=>setTab(x)} key={x}><Icon n={x==='home'?'home':x==='search'?'search':x==='library'?'music':x==='playlists'?'list':'user'}/><span>{t}</span></button>)}</nav>{full&&cur&&<div className="player"><button className="back" onClick={()=>setFull(false)}>‹ NOW PLAYING</button><Cover url={cur.url} big/><small>GAMEWAVE CLOUD</small><h1>{cur.title}</h1><p>{cur.artist}</p><button className={cur.favorite?'heart liked':'heart'} onClick={()=>fav(cur)}>♥</button><input type="range" min="0" max={dur||1} step=".1" value={Math.min(pos,dur||1)} onChange={e=>{if(audio.current)audio.current.currentTime=+e.target.value}}/><div className="times"><span>{fmt(pos)}</span><span>{fmt(dur)}</span></div><div className="controls"><button className={shuffle?'on':''} onClick={()=>setShuffle(!shuffle)}>⤨</button><button onClick={prev}>|◀</button><button className="bigplay" onClick={()=>playing?audio.current?.pause():audio.current?.play()}>{playing?'Ⅱ':'▶'}</button><button onClick={next}>▶|</button><button className={repeat?'on':''} onClick={()=>setRepeat(!repeat)}>↻</button></div></div>}{toast&&<div className="toast">{toast}</div>}</div>}
function Rows({list,play,fav,add,remove,togglePublic}:{list:Song[],play:(s:Song,l?:Song[])=>void,fav?:(s:Song)=>void,add?:(s:Song)=>void,remove?:(s:Song)=>void,togglePublic?:(s:Song)=>void}){return list.length?<div className="rows">{list.map(s=><div className="row" key={s.id}><button className="coverbtn" onClick={()=>play(s,list)}><Cover url={s.url}/></button><button className="song" onClick={()=>play(s,list)}><b>{s.title}</b><small>{s.artist} · {s.album}</small></button>{fav&&<button onClick={()=>fav(s)} className={s.favorite?'liked':''}>♥</button>}{add&&<button onClick={()=>add(s)}>＋</button>}{togglePublic&&<button title={s.is_public?'Public — tap to make private':'Private — tap to make public'} onClick={()=>togglePublic(s)} className={s.is_public?'liked':''}>{s.is_public?'🌐':'🔒'}</button>}{remove&&<button onClick={()=>remove(s)}>⌫</button>}</div>)}</div>:<div className="empty"><h3>No music found</h3></div>}
function Playlists({ps,songs,create,play}:{ps:Playlist[],songs:Song[],create:()=>void,play:(s:Song[],l?:Song[])=>void}){const[selected,setSelected]=useState<Playlist>();if(selected){const ss=songs.filter(s=>selected.songIds.includes(s.id));return <><button className="backlink" onClick={()=>setSelected(undefined)}>‹ Playlists</button><div className="playlistHead"><div className="playlistArt">♫</div><div><small>PLAYLIST</small><h1>{selected.name}</h1><p>{ss.length} tracks</p><button className="primary" onClick={()=>ss[0]&&play(ss)}>▶ Play All</button></div></div><Rows list={ss} play={play as any}/></>}return <><div className="title"><div><small>YOUR COLLECTIONS</small><h1>Playlists</h1><p>{ps.length} playlists</p></div><button className="primary" onClick={create}>＋ New Playlist</button></div>{ps.length?<div className="grid">{ps.map(x=><button className="pcard" key={x.id} onClick={()=>setSelected(x)}><div>♫</div><b>{x.name}</b><small>{x.songIds.length} tracks</small></button>)}</div>:<div className="empty"><h2>Create your first playlist</h2><button className="primary" onClick={create}>＋ New Playlist</button></div>}</>}
function Profile({songs,ps,email,signOut}:{songs:Song[],ps:Playlist[],email:string,signOut:()=>void}){return <><div className="profile"><div className="avatar">G</div><small>ACCOUNT</small><h1>GAMEWAVE User</h1><p>{email}</p></div><div className="stats"><div><b>{songs.length}</b><small>Tracks</small></div><div><b>{ps.length}</b><small>Playlists</small></div><div><b>{songs.filter(x=>x.favorite).length}</b><small>Favorites</small></div></div><div className="note"><b>Cloud storage aktif</b><p>Lagu tersimpan di Supabase Storage. Lagu yang ditandai <b>Public</b> dapat ditemukan dan diputar oleh akun lain, sedangkan lagu privat hanya terlihat oleh pemiliknya.</p></div><button className="danger" onClick={signOut}>Sign out</button></>}
createRoot(document.getElementById('root')!).render(<App/>);
